# Generated on Wed Aug 14 00:38:02 EDT 2019
kind: Service
apiVersion: v1
metadata:
  name: helloclient
  labels:
    app: helloclient
  namespace: hello
spec:
  type: LoadBalancer
  spec:
    ports:
    - port: 80
      targetPort: 8080
      name: helloclient
  selector:
    app: helloclient