---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudpipelines/pipeline-base
    tag: latest
inputs:
  - name: concourse
  - name: scripts
  - name: repo
  - name: keyval
outputs:
  - name: out
  - name: keyvalout
caches:
  - path: gradle
  - path: maven
run:
  path: concourse/src/tasks/task.sh
